language: cpp

compiler:
  - g++

before_script:
  # clean up
  - rm -rf bin
  - rm -rf lib
  - rm -rf build
  # create build folder
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build
