dist: xenial
language: cpp

os:
  - osx

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   addons: &gcc6 {apt: {packages: [g++-6] , sources: [ubuntu-toolchain-r-test]}}
    #   env: BUILD_TYPE=Coverage COMPILER_VER=6
    - os: linux
      compiler: gcc
      addons: {apt: {packages: [g++-6,doxygen] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Release COMPILER_VER=6 GEN_DOC=TRUE
    - os: linux # Use 3.8 since 3.9 is broken on trusty when using ASAN
      compiler: clang
      addons: &clang38 {apt: {packages: [clang-3.8,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Debug COMPILER_VER=3.8 USE_ASAN=1
    - os: linux
      compiler: clang
      addons: *clang38
      env: BUILD_TYPE=Debug COMPILER_VER=3.8 USE_UBSAN=1
    - os: linux
      compiler: clang
      addons: &clang39 {apt: {packages: [clang-3.9,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test,llvm-toolchain-trusty-3.9]}}
      env: BUILD_TYPE=Debug COMPILER_VER=3.9
    - os: linux
      compiler: clang
      addons: *clang39
      env: BUILD_TYPE=Release COMPILER_VER=3.9
    - os: linux
      compiler: clang
      addons: &clang4 {apt: {packages: [clang-4.0,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test,llvm-toolchain-trusty-4.0]}}
      env: BUILD_TYPE=Debug COMPILER_VER=4.0 USE_ASAN=1 LSAN_OPTIONS=verbosity=1:log_threads=1
      sudo: required
    - os: linux
      compiler: clang
      addons: *clang4
      env: BUILD_TYPE=Release COMPILER_VER=4.0 USE_UBSAN=1
    - os: linux
      compiler: clang
      addons: &clang6 {apt: {packages: [clang-6.0,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Debug COMPILER_VER=6.0 USE_ASAN=1 LSAN_OPTIONS=verbosity=1:log_threads=1
      sudo: required
    - os: linux
      compiler: clang
      addons: *clang6
      env: BUILD_TYPE=Release COMPILER_VER=6.0 USE_UBSAN=1

before_install:
  # Combine global build options with OS/compiler-dependent options
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  # Install dependencies for GLFW
  - sudo apt-get update
  - sudo apt-get install xorg-dev libglu1-mesa-dev

install:
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.18/cmake-3.18.1-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

before_script:
  # clean up
  - rm -rf bin
  - rm -rf lib
  - rm -rf build
  # create build folder
  - mkdir build
  - cd build

script:
  - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - make
