# Copyright 2020 Nghia Lam
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Version
version: '0.0.{build}'

# VM
image: Visual Studio 2017

# Global Maxtrix
environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

# Build
build_script:
  - cmake "-G%GENERATOR%" -H. -B builds -DENABLE_TESTING=1
  - cmake --build builds --config "%CONFIG%"
